### ISSUE TITLE
/Users/remy/Code/Ruby/sylrplm/app/models/statusobject.rb:27: warning: key :scope is duplicated and overwritten on line 27

### ISSUE THREAD

**Issue by rymai** [sylvani/sylrplm#12]
Je ne sais pas quel est la bonne valeur mais il faudrait corriger ça : `validates_uniqueness_of :name, scope: :forobject, scope: :rank`

Soit

```ruby
validates_uniqueness_of :name, scope: :forobject
```

soit

```ruby
validates_uniqueness_of :name, scope: :rank
```

ou soit

```ruby
validates_uniqueness_of :name, scope: [:forobject, :rank]
```

/cc @sylvani

**Comment by rymai** [comment]
Je vois que tu as poussé https://github.com/sylvani/sylrplm/commit/ec0242ae4d2fe5beeb2b04bb1aae077384b69d3d pour régler le problème !

**Comment by sylvani** [comment]
yes
